### ISSUE TITLE
executables for non-Windows platforms

### ISSUE THREAD

**Issue by vuphan314** [bethune-bryant/Easel#3]
Hello Bryant:

Are there executables of this SequenceL Easel game engine for other platforms, such as Ubuntu?

Thanks,
Vu

**Comment by bethune-bryant** [comment]
Hey Vu,

No There is not.

A year ago or so I looked at making one using the [CIMG](http://cimg.eu/) library. However, where C# handled various image formats(animated .gif, .png, .bmp, .jpg, etc) and sound formats(mp3, avi, etc.) very easily, at first glance it seemed that may be challenging to do only in C++.

Of course it should be rather straightforward to do some subset of functionality.

Let me know if you have any other questions.

Thanks,
-Bryant

**Comment by vuphan314** [comment]
Hi Bryant:

Thank you for letting me know.

I am closing this issue then.

Regards,
Vu
